---
- name: "install packages"
  apt:
    name: "*"
    update_cache: yes
    cache_valid_time: 3600

- name: "install packages"
  apt:
    name:
      - bind9
      - dnsdist
      - pdns-recursor
      - unbound
      - frr
    state: latest
